// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductManagement.Infrastructure;

#nullable disable

namespace ProductManagement.Infrastructure.Migrations
{
    [DbContext(typeof(ProductManagementDbContext))]
    [Migration("20250117081842_seed data with Sub category")]
    partial class seeddatawithSubcategory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProductManagement.Domain.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("InsertedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("ParentCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9b184e88-d905-4835-9e4f-20e9be869270"),
                            Description = "electronics Description",
                            InsertedBy = new Guid("8bfa8403-c87e-4332-b758-efd799d30cf9"),
                            InsertedDate = new DateTime(2025, 1, 17, 10, 18, 42, 518, DateTimeKind.Local).AddTicks(9487),
                            IsDeleted = false,
                            Name = "electronics",
                            Status = (byte)1
                        },
                        new
                        {
                            Id = new Guid("a1f1b456-fcbb-4139-a15d-6dd8e8dfa267"),
                            Description = "electronics SEHG9 Description",
                            InsertedBy = new Guid("8bfa8403-c87e-4332-b758-efd799d30cf9"),
                            InsertedDate = new DateTime(2025, 1, 17, 10, 18, 42, 518, DateTimeKind.Local).AddTicks(9487),
                            IsDeleted = false,
                            Name = "electronics SEHG9",
                            ParentCategoryId = new Guid("9b184e88-d905-4835-9e4f-20e9be869270"),
                            Status = (byte)1
                        },
                        new
                        {
                            Id = new Guid("e83c05ad-a0ad-4bb1-b782-2d8ad3f299e5"),
                            Description = "electronics PZ39W Description",
                            InsertedBy = new Guid("8bfa8403-c87e-4332-b758-efd799d30cf9"),
                            InsertedDate = new DateTime(2025, 1, 17, 10, 18, 42, 518, DateTimeKind.Local).AddTicks(9487),
                            IsDeleted = false,
                            Name = "electronics PZ39W",
                            ParentCategoryId = new Guid("9b184e88-d905-4835-9e4f-20e9be869270"),
                            Status = (byte)1
                        },
                        new
                        {
                            Id = new Guid("23688319-5326-44b3-b4c9-fc5367778bad"),
                            Description = "electronics VPHEN Description",
                            InsertedBy = new Guid("8bfa8403-c87e-4332-b758-efd799d30cf9"),
                            InsertedDate = new DateTime(2025, 1, 17, 10, 18, 42, 518, DateTimeKind.Local).AddTicks(9487),
                            IsDeleted = false,
                            Name = "electronics VPHEN",
                            ParentCategoryId = new Guid("9b184e88-d905-4835-9e4f-20e9be869270"),
                            Status = (byte)1
                        },
                        new
                        {
                            Id = new Guid("b12a048f-0637-4677-98d7-4af22bcc12de"),
                            Description = "electronics 2SHY2 Description",
                            InsertedBy = new Guid("8bfa8403-c87e-4332-b758-efd799d30cf9"),
                            InsertedDate = new DateTime(2025, 1, 17, 10, 18, 42, 518, DateTimeKind.Local).AddTicks(9487),
                            IsDeleted = false,
                            Name = "electronics 2SHY2",
                            ParentCategoryId = new Guid("9b184e88-d905-4835-9e4f-20e9be869270"),
                            Status = (byte)1
                        },
                        new
                        {
                            Id = new Guid("0b2b42be-7db5-44f6-a0a4-78ab09302772"),
                            Description = "electronics MA4Y0 Description",
                            InsertedBy = new Guid("8bfa8403-c87e-4332-b758-efd799d30cf9"),
                            InsertedDate = new DateTime(2025, 1, 17, 10, 18, 42, 518, DateTimeKind.Local).AddTicks(9487),
                            IsDeleted = false,
                            Name = "electronics MA4Y0",
                            ParentCategoryId = new Guid("9b184e88-d905-4835-9e4f-20e9be869270"),
                            Status = (byte)1
                        },
                        new
                        {
                            Id = new Guid("167cccb0-cc6a-4afd-9891-0b1d3331212e"),
                            Description = "electronics XJTQX Description",
                            InsertedBy = new Guid("8bfa8403-c87e-4332-b758-efd799d30cf9"),
                            InsertedDate = new DateTime(2025, 1, 17, 10, 18, 42, 518, DateTimeKind.Local).AddTicks(9487),
                            IsDeleted = false,
                            Name = "electronics XJTQX",
                            ParentCategoryId = new Guid("9b184e88-d905-4835-9e4f-20e9be869270"),
                            Status = (byte)1
                        },
                        new
                        {
                            Id = new Guid("213d649d-acb8-4427-928a-8d465113730c"),
                            Description = "electronics 0921R Description",
                            InsertedBy = new Guid("8bfa8403-c87e-4332-b758-efd799d30cf9"),
                            InsertedDate = new DateTime(2025, 1, 17, 10, 18, 42, 518, DateTimeKind.Local).AddTicks(9487),
                            IsDeleted = false,
                            Name = "electronics 0921R",
                            ParentCategoryId = new Guid("9b184e88-d905-4835-9e4f-20e9be869270"),
                            Status = (byte)1
                        },
                        new
                        {
                            Id = new Guid("5f602127-55fa-4e12-a603-cdb4e6098d87"),
                            Description = "electronics 7GMLR Description",
                            InsertedBy = new Guid("8bfa8403-c87e-4332-b758-efd799d30cf9"),
                            InsertedDate = new DateTime(2025, 1, 17, 10, 18, 42, 518, DateTimeKind.Local).AddTicks(9487),
                            IsDeleted = false,
                            Name = "electronics 7GMLR",
                            ParentCategoryId = new Guid("9b184e88-d905-4835-9e4f-20e9be869270"),
                            Status = (byte)1
                        },
                        new
                        {
                            Id = new Guid("ec82c98d-dd8b-4894-8072-3fd1628ddb7d"),
                            Description = "electronics 61H9Z Description",
                            InsertedBy = new Guid("8bfa8403-c87e-4332-b758-efd799d30cf9"),
                            InsertedDate = new DateTime(2025, 1, 17, 10, 18, 42, 518, DateTimeKind.Local).AddTicks(9487),
                            IsDeleted = false,
                            Name = "electronics 61H9Z",
                            ParentCategoryId = new Guid("9b184e88-d905-4835-9e4f-20e9be869270"),
                            Status = (byte)1
                        },
                        new
                        {
                            Id = new Guid("67c0bcd7-96c0-4732-b8de-4e168d0a02b1"),
                            Description = "electronics 87KT6 Description",
                            InsertedBy = new Guid("8bfa8403-c87e-4332-b758-efd799d30cf9"),
                            InsertedDate = new DateTime(2025, 1, 17, 10, 18, 42, 518, DateTimeKind.Local).AddTicks(9487),
                            IsDeleted = false,
                            Name = "electronics 87KT6",
                            ParentCategoryId = new Guid("9b184e88-d905-4835-9e4f-20e9be869270"),
                            Status = (byte)1
                        },
                        new
                        {
                            Id = new Guid("df5f17d5-88a5-4bd5-941e-2d3c4bea9bc1"),
                            Description = "electronics OUFJK Description",
                            InsertedBy = new Guid("8bfa8403-c87e-4332-b758-efd799d30cf9"),
                            InsertedDate = new DateTime(2025, 1, 17, 10, 18, 42, 518, DateTimeKind.Local).AddTicks(9487),
                            IsDeleted = false,
                            Name = "electronics OUFJK",
                            ParentCategoryId = new Guid("9b184e88-d905-4835-9e4f-20e9be869270"),
                            Status = (byte)1
                        },
                        new
                        {
                            Id = new Guid("972686da-f1d9-49f2-9656-b37fb6cc72fd"),
                            Description = "electronics JRAAU Description",
                            InsertedBy = new Guid("8bfa8403-c87e-4332-b758-efd799d30cf9"),
                            InsertedDate = new DateTime(2025, 1, 17, 10, 18, 42, 518, DateTimeKind.Local).AddTicks(9487),
                            IsDeleted = false,
                            Name = "electronics JRAAU",
                            ParentCategoryId = new Guid("9b184e88-d905-4835-9e4f-20e9be869270"),
                            Status = (byte)1
                        },
                        new
                        {
                            Id = new Guid("d4ebef1c-194c-49a1-b6ae-a30d1c112a5b"),
                            Description = "electronics ZLQOP Description",
                            InsertedBy = new Guid("8bfa8403-c87e-4332-b758-efd799d30cf9"),
                            InsertedDate = new DateTime(2025, 1, 17, 10, 18, 42, 518, DateTimeKind.Local).AddTicks(9487),
                            IsDeleted = false,
                            Name = "electronics ZLQOP",
                            ParentCategoryId = new Guid("9b184e88-d905-4835-9e4f-20e9be869270"),
                            Status = (byte)1
                        },
                        new
                        {
                            Id = new Guid("cb803d35-5a7c-4503-b417-b6249873bb15"),
                            Description = "electronics S5IUH Description",
                            InsertedBy = new Guid("8bfa8403-c87e-4332-b758-efd799d30cf9"),
                            InsertedDate = new DateTime(2025, 1, 17, 10, 18, 42, 518, DateTimeKind.Local).AddTicks(9487),
                            IsDeleted = false,
                            Name = "electronics S5IUH",
                            ParentCategoryId = new Guid("9b184e88-d905-4835-9e4f-20e9be869270"),
                            Status = (byte)1
                        },
                        new
                        {
                            Id = new Guid("499f7d3f-8c6d-4814-9a2e-365b52c62ff1"),
                            Description = "electronics I38SC Description",
                            InsertedBy = new Guid("8bfa8403-c87e-4332-b758-efd799d30cf9"),
                            InsertedDate = new DateTime(2025, 1, 17, 10, 18, 42, 518, DateTimeKind.Local).AddTicks(9487),
                            IsDeleted = false,
                            Name = "electronics I38SC",
                            ParentCategoryId = new Guid("9b184e88-d905-4835-9e4f-20e9be869270"),
                            Status = (byte)1
                        },
                        new
                        {
                            Id = new Guid("ffe4e268-9a62-480c-8606-cdb4787f779a"),
                            Description = "electronics Z6NYS Description",
                            InsertedBy = new Guid("8bfa8403-c87e-4332-b758-efd799d30cf9"),
                            InsertedDate = new DateTime(2025, 1, 17, 10, 18, 42, 518, DateTimeKind.Local).AddTicks(9487),
                            IsDeleted = false,
                            Name = "electronics Z6NYS",
                            ParentCategoryId = new Guid("9b184e88-d905-4835-9e4f-20e9be869270"),
                            Status = (byte)1
                        },
                        new
                        {
                            Id = new Guid("f79fca94-47c0-4215-aac2-540c57e6dd6f"),
                            Description = "electronics 8DSRI Description",
                            InsertedBy = new Guid("8bfa8403-c87e-4332-b758-efd799d30cf9"),
                            InsertedDate = new DateTime(2025, 1, 17, 10, 18, 42, 518, DateTimeKind.Local).AddTicks(9487),
                            IsDeleted = false,
                            Name = "electronics 8DSRI",
                            ParentCategoryId = new Guid("9b184e88-d905-4835-9e4f-20e9be869270"),
                            Status = (byte)1
                        },
                        new
                        {
                            Id = new Guid("d2576100-fff1-4ee1-9a14-b0dc07726e0c"),
                            Description = "electronics 4031A Description",
                            InsertedBy = new Guid("8bfa8403-c87e-4332-b758-efd799d30cf9"),
                            InsertedDate = new DateTime(2025, 1, 17, 10, 18, 42, 518, DateTimeKind.Local).AddTicks(9487),
                            IsDeleted = false,
                            Name = "electronics 4031A",
                            ParentCategoryId = new Guid("9b184e88-d905-4835-9e4f-20e9be869270"),
                            Status = (byte)1
                        },
                        new
                        {
                            Id = new Guid("0c0eea9e-9a72-496a-b30f-69ab6c629473"),
                            Description = "clothing Description",
                            InsertedBy = new Guid("8bfa8403-c87e-4332-b758-efd799d30cf9"),
                            InsertedDate = new DateTime(2025, 1, 17, 10, 18, 42, 518, DateTimeKind.Local).AddTicks(9487),
                            IsDeleted = false,
                            Name = "clothing",
                            Status = (byte)1
                        },
                        new
                        {
                            Id = new Guid("1cca563b-c04a-4678-861d-039b965cf2ce"),
                            Description = "clothing 0UJPH Description",
                            InsertedBy = new Guid("8bfa8403-c87e-4332-b758-efd799d30cf9"),
                            InsertedDate = new DateTime(2025, 1, 17, 10, 18, 42, 518, DateTimeKind.Local).AddTicks(9487),
                            IsDeleted = false,
                            Name = "clothing 0UJPH",
                            ParentCategoryId = new Guid("0c0eea9e-9a72-496a-b30f-69ab6c629473"),
                            Status = (byte)1
                        },
                        new
                        {
                            Id = new Guid("e80c8906-f679-45f1-b094-2af95a65ab9a"),
                            Description = "clothing 02AUB Description",
                            InsertedBy = new Guid("8bfa8403-c87e-4332-b758-efd799d30cf9"),
                            InsertedDate = new DateTime(2025, 1, 17, 10, 18, 42, 518, DateTimeKind.Local).AddTicks(9487),
                            IsDeleted = false,
                            Name = "clothing 02AUB",
                            ParentCategoryId = new Guid("0c0eea9e-9a72-496a-b30f-69ab6c629473"),
                            Status = (byte)1
                        },
                        new
                        {
                            Id = new Guid("c4d615d9-14b8-4277-89fe-01253a4afc05"),
                            Description = "clothing T2678 Description",
                            InsertedBy = new Guid("8bfa8403-c87e-4332-b758-efd799d30cf9"),
                            InsertedDate = new DateTime(2025, 1, 17, 10, 18, 42, 518, DateTimeKind.Local).AddTicks(9487),
                            IsDeleted = false,
                            Name = "clothing T2678",
                            ParentCategoryId = new Guid("0c0eea9e-9a72-496a-b30f-69ab6c629473"),
                            Status = (byte)1
                        },
                        new
                        {
                            Id = new Guid("fb18d937-3182-4c1c-bf9c-4ac1871aaa08"),
                            Description = "clothing LCEID Description",
                            InsertedBy = new Guid("8bfa8403-c87e-4332-b758-efd799d30cf9"),
                            InsertedDate = new DateTime(2025, 1, 17, 10, 18, 42, 518, DateTimeKind.Local).AddTicks(9487),
                            IsDeleted = false,
                            Name = "clothing LCEID",
                            ParentCategoryId = new Guid("0c0eea9e-9a72-496a-b30f-69ab6c629473"),
                            Status = (byte)1
                        },
                        new
                        {
                            Id = new Guid("71e895d2-fb56-4278-91b3-ac2c30dec74d"),
                            Description = "clothing LXMG2 Description",
                            InsertedBy = new Guid("8bfa8403-c87e-4332-b758-efd799d30cf9"),
                            InsertedDate = new DateTime(2025, 1, 17, 10, 18, 42, 518, DateTimeKind.Local).AddTicks(9487),
                            IsDeleted = false,
                            Name = "clothing LXMG2",
                            ParentCategoryId = new Guid("0c0eea9e-9a72-496a-b30f-69ab6c629473"),
                            Status = (byte)1
                        },
                        new
                        {
                            Id = new Guid("2c8db109-d414-460f-827d-bcaf9cd1aeee"),
                            Description = "clothing JQBP7 Description",
                            InsertedBy = new Guid("8bfa8403-c87e-4332-b758-efd799d30cf9"),
                            InsertedDate = new DateTime(2025, 1, 17, 10, 18, 42, 518, DateTimeKind.Local).AddTicks(9487),
                            IsDeleted = false,
                            Name = "clothing JQBP7",
                            ParentCategoryId = new Guid("0c0eea9e-9a72-496a-b30f-69ab6c629473"),
                            Status = (byte)1
                        },
                        new
                        {
                            Id = new Guid("66beb5ff-ca68-40b1-a516-c06901b2af03"),
                            Description = "clothing 7JKCH Description",
                            InsertedBy = new Guid("8bfa8403-c87e-4332-b758-efd799d30cf9"),
                            InsertedDate = new DateTime(2025, 1, 17, 10, 18, 42, 518, DateTimeKind.Local).AddTicks(9487),
                            IsDeleted = false,
                            Name = "clothing 7JKCH",
                            ParentCategoryId = new Guid("0c0eea9e-9a72-496a-b30f-69ab6c629473"),
                            Status = (byte)1
                        },
                        new
                        {
                            Id = new Guid("3865a01a-e2ab-44ac-8545-0e951468e25e"),
                            Description = "clothing IZ3C8 Description",
                            InsertedBy = new Guid("8bfa8403-c87e-4332-b758-efd799d30cf9"),
                            InsertedDate = new DateTime(2025, 1, 17, 10, 18, 42, 518, DateTimeKind.Local).AddTicks(9487),
                            IsDeleted = false,
                            Name = "clothing IZ3C8",
                            ParentCategoryId = new Guid("0c0eea9e-9a72-496a-b30f-69ab6c629473"),
                            Status = (byte)1
                        },
                        new
                        {
                            Id = new Guid("47fe4807-c4fc-4f89-ac70-0a9729c453a4"),
                            Description = "clothing YWH6T Description",
                            InsertedBy = new Guid("8bfa8403-c87e-4332-b758-efd799d30cf9"),
                            InsertedDate = new DateTime(2025, 1, 17, 10, 18, 42, 518, DateTimeKind.Local).AddTicks(9487),
                            IsDeleted = false,
                            Name = "clothing YWH6T",
                            ParentCategoryId = new Guid("0c0eea9e-9a72-496a-b30f-69ab6c629473"),
                            Status = (byte)1
                        },
                        new
                        {
                            Id = new Guid("5b34c52a-ec54-458b-bf4a-98de6fb69ac8"),
                            Description = "clothing 3RVP9 Description",
                            InsertedBy = new Guid("8bfa8403-c87e-4332-b758-efd799d30cf9"),
                            InsertedDate = new DateTime(2025, 1, 17, 10, 18, 42, 518, DateTimeKind.Local).AddTicks(9487),
                            IsDeleted = false,
                            Name = "clothing 3RVP9",
                            ParentCategoryId = new Guid("0c0eea9e-9a72-496a-b30f-69ab6c629473"),
                            Status = (byte)1
                        },
                        new
                        {
                            Id = new Guid("80a96349-60f4-44ca-86df-d9d10136ccfd"),
                            Description = "clothing IDPV6 Description",
                            InsertedBy = new Guid("8bfa8403-c87e-4332-b758-efd799d30cf9"),
                            InsertedDate = new DateTime(2025, 1, 17, 10, 18, 42, 518, DateTimeKind.Local).AddTicks(9487),
                            IsDeleted = false,
                            Name = "clothing IDPV6",
                            ParentCategoryId = new Guid("0c0eea9e-9a72-496a-b30f-69ab6c629473"),
                            Status = (byte)1
                        },
                        new
                        {
                            Id = new Guid("e14ab559-a6a5-4f46-9955-9470cd906202"),
                            Description = "clothing OPW7N Description",
                            InsertedBy = new Guid("8bfa8403-c87e-4332-b758-efd799d30cf9"),
                            InsertedDate = new DateTime(2025, 1, 17, 10, 18, 42, 518, DateTimeKind.Local).AddTicks(9487),
                            IsDeleted = false,
                            Name = "clothing OPW7N",
                            ParentCategoryId = new Guid("0c0eea9e-9a72-496a-b30f-69ab6c629473"),
                            Status = (byte)1
                        },
                        new
                        {
                            Id = new Guid("dc25e4e3-c1a7-4521-b1c0-e732943ecc07"),
                            Description = "clothing TYWRN Description",
                            InsertedBy = new Guid("8bfa8403-c87e-4332-b758-efd799d30cf9"),
                            InsertedDate = new DateTime(2025, 1, 17, 10, 18, 42, 518, DateTimeKind.Local).AddTicks(9487),
                            IsDeleted = false,
                            Name = "clothing TYWRN",
                            ParentCategoryId = new Guid("0c0eea9e-9a72-496a-b30f-69ab6c629473"),
                            Status = (byte)1
                        },
                        new
                        {
                            Id = new Guid("7199fd0a-cc03-46f0-9d21-2ad2e1ef8cbe"),
                            Description = "groceries Description",
                            InsertedBy = new Guid("8bfa8403-c87e-4332-b758-efd799d30cf9"),
                            InsertedDate = new DateTime(2025, 1, 17, 10, 18, 42, 518, DateTimeKind.Local).AddTicks(9487),
                            IsDeleted = false,
                            Name = "groceries",
                            Status = (byte)1
                        },
                        new
                        {
                            Id = new Guid("b3f4b0a9-a73f-418a-bfb1-2c885bd34ed5"),
                            Description = "groceries DVK3Y Description",
                            InsertedBy = new Guid("8bfa8403-c87e-4332-b758-efd799d30cf9"),
                            InsertedDate = new DateTime(2025, 1, 17, 10, 18, 42, 518, DateTimeKind.Local).AddTicks(9487),
                            IsDeleted = false,
                            Name = "groceries DVK3Y",
                            ParentCategoryId = new Guid("7199fd0a-cc03-46f0-9d21-2ad2e1ef8cbe"),
                            Status = (byte)1
                        },
                        new
                        {
                            Id = new Guid("a41c1967-b118-4a98-afcc-8ee9929e12be"),
                            Description = "groceries IK2ZT Description",
                            InsertedBy = new Guid("8bfa8403-c87e-4332-b758-efd799d30cf9"),
                            InsertedDate = new DateTime(2025, 1, 17, 10, 18, 42, 518, DateTimeKind.Local).AddTicks(9487),
                            IsDeleted = false,
                            Name = "groceries IK2ZT",
                            ParentCategoryId = new Guid("7199fd0a-cc03-46f0-9d21-2ad2e1ef8cbe"),
                            Status = (byte)1
                        },
                        new
                        {
                            Id = new Guid("6ff655b0-b1aa-40bd-acba-df07dfd61600"),
                            Description = "groceries 4FS5A Description",
                            InsertedBy = new Guid("8bfa8403-c87e-4332-b758-efd799d30cf9"),
                            InsertedDate = new DateTime(2025, 1, 17, 10, 18, 42, 518, DateTimeKind.Local).AddTicks(9487),
                            IsDeleted = false,
                            Name = "groceries 4FS5A",
                            ParentCategoryId = new Guid("7199fd0a-cc03-46f0-9d21-2ad2e1ef8cbe"),
                            Status = (byte)1
                        },
                        new
                        {
                            Id = new Guid("5c6c4f20-9ac2-421e-8416-45fd0fba87ff"),
                            Description = "groceries 76JGL Description",
                            InsertedBy = new Guid("8bfa8403-c87e-4332-b758-efd799d30cf9"),
                            InsertedDate = new DateTime(2025, 1, 17, 10, 18, 42, 518, DateTimeKind.Local).AddTicks(9487),
                            IsDeleted = false,
                            Name = "groceries 76JGL",
                            ParentCategoryId = new Guid("7199fd0a-cc03-46f0-9d21-2ad2e1ef8cbe"),
                            Status = (byte)1
                        });
                });

            modelBuilder.Entity("ProductManagement.Domain.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("InsertedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bb0b13db-5a10-45a1-90fd-056d74237165"),
                            CategoryId = new Guid("a1f1b456-fcbb-4139-a15d-6dd8e8dfa267"),
                            Description = "SJNSHHHXOY77W0TQ0TQW",
                            InsertedBy = new Guid("8bfa8403-c87e-4332-b758-efd799d30cf9"),
                            InsertedDate = new DateTime(2025, 1, 17, 10, 18, 42, 518, DateTimeKind.Local).AddTicks(9487),
                            IsDeleted = false,
                            Name = "O75FK",
                            Price = 699.99m,
                            Status = (byte)1,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = new Guid("25d5b126-ee5e-4d12-8e4d-625312b3429f"),
                            CategoryId = new Guid("e83c05ad-a0ad-4bb1-b782-2d8ad3f299e5"),
                            Description = "8047N6BZSG3SY1MP3YBN",
                            InsertedBy = new Guid("8bfa8403-c87e-4332-b758-efd799d30cf9"),
                            InsertedDate = new DateTime(2025, 1, 17, 10, 18, 42, 518, DateTimeKind.Local).AddTicks(9487),
                            IsDeleted = false,
                            Name = "KZLC7",
                            Price = 699.99m,
                            Status = (byte)1,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = new Guid("b3d86704-07db-4fa7-839e-46e8c4d07ad0"),
                            CategoryId = new Guid("23688319-5326-44b3-b4c9-fc5367778bad"),
                            Description = "14ZCR7PXMAHM6XDXFYB2",
                            InsertedBy = new Guid("8bfa8403-c87e-4332-b758-efd799d30cf9"),
                            InsertedDate = new DateTime(2025, 1, 17, 10, 18, 42, 518, DateTimeKind.Local).AddTicks(9487),
                            IsDeleted = false,
                            Name = "1BQ79",
                            Price = 699.99m,
                            Status = (byte)1,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = new Guid("ab58f02c-b053-48c2-b91b-5693f43299c1"),
                            CategoryId = new Guid("b12a048f-0637-4677-98d7-4af22bcc12de"),
                            Description = "CWIXE8PZL5U0WKVGCYWP",
                            InsertedBy = new Guid("8bfa8403-c87e-4332-b758-efd799d30cf9"),
                            InsertedDate = new DateTime(2025, 1, 17, 10, 18, 42, 518, DateTimeKind.Local).AddTicks(9487),
                            IsDeleted = false,
                            Name = "0GOTW",
                            Price = 699.99m,
                            Status = (byte)1,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = new Guid("cac2234a-5513-47fd-9afd-18ced8f9992c"),
                            CategoryId = new Guid("0b2b42be-7db5-44f6-a0a4-78ab09302772"),
                            Description = "3O2QRN3VJXT0NOS2FPQR",
                            InsertedBy = new Guid("8bfa8403-c87e-4332-b758-efd799d30cf9"),
                            InsertedDate = new DateTime(2025, 1, 17, 10, 18, 42, 518, DateTimeKind.Local).AddTicks(9487),
                            IsDeleted = false,
                            Name = "ZJDR9",
                            Price = 699.99m,
                            Status = (byte)1,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = new Guid("63290733-89d6-4ca4-b988-9bc858b0a96e"),
                            CategoryId = new Guid("167cccb0-cc6a-4afd-9891-0b1d3331212e"),
                            Description = "PWTNCHKUKXREEZLVLRBX",
                            InsertedBy = new Guid("8bfa8403-c87e-4332-b758-efd799d30cf9"),
                            InsertedDate = new DateTime(2025, 1, 17, 10, 18, 42, 518, DateTimeKind.Local).AddTicks(9487),
                            IsDeleted = false,
                            Name = "0PAQ2",
                            Price = 699.99m,
                            Status = (byte)1,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = new Guid("8677a79a-f980-4726-a352-727237e00c56"),
                            CategoryId = new Guid("213d649d-acb8-4427-928a-8d465113730c"),
                            Description = "RLUHRRD49K6CMIKZBV10",
                            InsertedBy = new Guid("8bfa8403-c87e-4332-b758-efd799d30cf9"),
                            InsertedDate = new DateTime(2025, 1, 17, 10, 18, 42, 518, DateTimeKind.Local).AddTicks(9487),
                            IsDeleted = false,
                            Name = "NGPOG",
                            Price = 699.99m,
                            Status = (byte)1,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = new Guid("4e1cc65a-506f-42a2-a16a-6cbf841f40d0"),
                            CategoryId = new Guid("5f602127-55fa-4e12-a603-cdb4e6098d87"),
                            Description = "PS7BBONPBT34O5H7UA2P",
                            InsertedBy = new Guid("8bfa8403-c87e-4332-b758-efd799d30cf9"),
                            InsertedDate = new DateTime(2025, 1, 17, 10, 18, 42, 518, DateTimeKind.Local).AddTicks(9487),
                            IsDeleted = false,
                            Name = "OCZAC",
                            Price = 699.99m,
                            Status = (byte)1,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = new Guid("5b69dfb3-82ab-4953-b822-b0e0beb65f08"),
                            CategoryId = new Guid("ec82c98d-dd8b-4894-8072-3fd1628ddb7d"),
                            Description = "YPOILWZZOY5HUS0TS6D7",
                            InsertedBy = new Guid("8bfa8403-c87e-4332-b758-efd799d30cf9"),
                            InsertedDate = new DateTime(2025, 1, 17, 10, 18, 42, 518, DateTimeKind.Local).AddTicks(9487),
                            IsDeleted = false,
                            Name = "4L6IQ",
                            Price = 699.99m,
                            Status = (byte)1,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = new Guid("672f5360-0913-4ce3-bd52-f90fcaafe791"),
                            CategoryId = new Guid("67c0bcd7-96c0-4732-b8de-4e168d0a02b1"),
                            Description = "CSLVCYE8NJQ1U5IUS8LA",
                            InsertedBy = new Guid("8bfa8403-c87e-4332-b758-efd799d30cf9"),
                            InsertedDate = new DateTime(2025, 1, 17, 10, 18, 42, 518, DateTimeKind.Local).AddTicks(9487),
                            IsDeleted = false,
                            Name = "8LVFQ",
                            Price = 699.99m,
                            Status = (byte)1,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = new Guid("36753cd4-6c00-4e8d-b87a-f94a3dbfe678"),
                            CategoryId = new Guid("df5f17d5-88a5-4bd5-941e-2d3c4bea9bc1"),
                            Description = "NIB3KRHGIA2SC0RPBOXA",
                            InsertedBy = new Guid("8bfa8403-c87e-4332-b758-efd799d30cf9"),
                            InsertedDate = new DateTime(2025, 1, 17, 10, 18, 42, 518, DateTimeKind.Local).AddTicks(9487),
                            IsDeleted = false,
                            Name = "QGZW7",
                            Price = 699.99m,
                            Status = (byte)1,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = new Guid("34b006e2-a228-4808-96b8-312df853527b"),
                            CategoryId = new Guid("972686da-f1d9-49f2-9656-b37fb6cc72fd"),
                            Description = "5BEO2WAT66Z0MSJRIEWL",
                            InsertedBy = new Guid("8bfa8403-c87e-4332-b758-efd799d30cf9"),
                            InsertedDate = new DateTime(2025, 1, 17, 10, 18, 42, 518, DateTimeKind.Local).AddTicks(9487),
                            IsDeleted = false,
                            Name = "R3V2I",
                            Price = 699.99m,
                            Status = (byte)1,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = new Guid("a984977a-8442-4afb-83e8-1fd95b993777"),
                            CategoryId = new Guid("d4ebef1c-194c-49a1-b6ae-a30d1c112a5b"),
                            Description = "HI0CN1KLRFMEM5AVA5T4",
                            InsertedBy = new Guid("8bfa8403-c87e-4332-b758-efd799d30cf9"),
                            InsertedDate = new DateTime(2025, 1, 17, 10, 18, 42, 518, DateTimeKind.Local).AddTicks(9487),
                            IsDeleted = false,
                            Name = "JBZB0",
                            Price = 699.99m,
                            Status = (byte)1,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = new Guid("a0634f42-606a-4e38-869c-11176ddeaea4"),
                            CategoryId = new Guid("cb803d35-5a7c-4503-b417-b6249873bb15"),
                            Description = "MTFBEUXUUWBGUEJ4DFUN",
                            InsertedBy = new Guid("8bfa8403-c87e-4332-b758-efd799d30cf9"),
                            InsertedDate = new DateTime(2025, 1, 17, 10, 18, 42, 518, DateTimeKind.Local).AddTicks(9487),
                            IsDeleted = false,
                            Name = "WZ8ZB",
                            Price = 699.99m,
                            Status = (byte)1,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = new Guid("3d7fdd04-eb28-4174-86a1-6bb1be759938"),
                            CategoryId = new Guid("499f7d3f-8c6d-4814-9a2e-365b52c62ff1"),
                            Description = "H6LMAVDQUUZ8LZTR9GIP",
                            InsertedBy = new Guid("8bfa8403-c87e-4332-b758-efd799d30cf9"),
                            InsertedDate = new DateTime(2025, 1, 17, 10, 18, 42, 518, DateTimeKind.Local).AddTicks(9487),
                            IsDeleted = false,
                            Name = "P4H1F",
                            Price = 699.99m,
                            Status = (byte)1,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = new Guid("7f15dc12-e451-4eb1-9a13-d062c4f2ad9e"),
                            CategoryId = new Guid("ffe4e268-9a62-480c-8606-cdb4787f779a"),
                            Description = "IDS8NO4Z3L7HJG2QAU2V",
                            InsertedBy = new Guid("8bfa8403-c87e-4332-b758-efd799d30cf9"),
                            InsertedDate = new DateTime(2025, 1, 17, 10, 18, 42, 518, DateTimeKind.Local).AddTicks(9487),
                            IsDeleted = false,
                            Name = "8GB4R",
                            Price = 699.99m,
                            Status = (byte)1,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = new Guid("28efe428-0f7c-42e7-96c6-6ffd5b637356"),
                            CategoryId = new Guid("f79fca94-47c0-4215-aac2-540c57e6dd6f"),
                            Description = "HUJJB9CZLYAQWXQ31JYX",
                            InsertedBy = new Guid("8bfa8403-c87e-4332-b758-efd799d30cf9"),
                            InsertedDate = new DateTime(2025, 1, 17, 10, 18, 42, 518, DateTimeKind.Local).AddTicks(9487),
                            IsDeleted = false,
                            Name = "U3I6C",
                            Price = 699.99m,
                            Status = (byte)1,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = new Guid("e94c1d0e-2ed9-4c9b-bac5-bee11d723039"),
                            CategoryId = new Guid("d2576100-fff1-4ee1-9a14-b0dc07726e0c"),
                            Description = "E4J7Y4SFNQZIYJU0S9P7",
                            InsertedBy = new Guid("8bfa8403-c87e-4332-b758-efd799d30cf9"),
                            InsertedDate = new DateTime(2025, 1, 17, 10, 18, 42, 518, DateTimeKind.Local).AddTicks(9487),
                            IsDeleted = false,
                            Name = "6PYUR",
                            Price = 699.99m,
                            Status = (byte)1,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = new Guid("eb2c0e07-172d-443a-9ece-8e4e8f296392"),
                            CategoryId = new Guid("1cca563b-c04a-4678-861d-039b965cf2ce"),
                            Description = "7TS02USOWH0QT99K5RST",
                            InsertedBy = new Guid("8bfa8403-c87e-4332-b758-efd799d30cf9"),
                            InsertedDate = new DateTime(2025, 1, 17, 10, 18, 42, 518, DateTimeKind.Local).AddTicks(9487),
                            IsDeleted = false,
                            Name = "SA2MI",
                            Price = 699.99m,
                            Status = (byte)1,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = new Guid("6c31740b-fbce-4158-9ba0-e4f86f65c58b"),
                            CategoryId = new Guid("e80c8906-f679-45f1-b094-2af95a65ab9a"),
                            Description = "M378F69AWN690UA3KRMS",
                            InsertedBy = new Guid("8bfa8403-c87e-4332-b758-efd799d30cf9"),
                            InsertedDate = new DateTime(2025, 1, 17, 10, 18, 42, 518, DateTimeKind.Local).AddTicks(9487),
                            IsDeleted = false,
                            Name = "VQCOH",
                            Price = 699.99m,
                            Status = (byte)1,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = new Guid("b05882df-ea1f-455e-af30-2013cce5cce9"),
                            CategoryId = new Guid("c4d615d9-14b8-4277-89fe-01253a4afc05"),
                            Description = "26T5CMNSEQ1QVLTXOCIP",
                            InsertedBy = new Guid("8bfa8403-c87e-4332-b758-efd799d30cf9"),
                            InsertedDate = new DateTime(2025, 1, 17, 10, 18, 42, 518, DateTimeKind.Local).AddTicks(9487),
                            IsDeleted = false,
                            Name = "8ET30",
                            Price = 699.99m,
                            Status = (byte)1,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = new Guid("e6e9be7b-a188-4831-adc6-c1be9b0431b8"),
                            CategoryId = new Guid("fb18d937-3182-4c1c-bf9c-4ac1871aaa08"),
                            Description = "BV3WWA68ZNGG7SQFUUB7",
                            InsertedBy = new Guid("8bfa8403-c87e-4332-b758-efd799d30cf9"),
                            InsertedDate = new DateTime(2025, 1, 17, 10, 18, 42, 518, DateTimeKind.Local).AddTicks(9487),
                            IsDeleted = false,
                            Name = "NQFAW",
                            Price = 699.99m,
                            Status = (byte)1,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = new Guid("d7178542-3aa7-4b3e-94ee-44faa57222f0"),
                            CategoryId = new Guid("71e895d2-fb56-4278-91b3-ac2c30dec74d"),
                            Description = "Q8H63PM00DN5JOKAGVXQ",
                            InsertedBy = new Guid("8bfa8403-c87e-4332-b758-efd799d30cf9"),
                            InsertedDate = new DateTime(2025, 1, 17, 10, 18, 42, 518, DateTimeKind.Local).AddTicks(9487),
                            IsDeleted = false,
                            Name = "0KDF7",
                            Price = 699.99m,
                            Status = (byte)1,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = new Guid("716ec7e9-48cb-49c6-ba3e-ff9dcb4945d9"),
                            CategoryId = new Guid("2c8db109-d414-460f-827d-bcaf9cd1aeee"),
                            Description = "TO40L8YGRZ7PN0BYTLYH",
                            InsertedBy = new Guid("8bfa8403-c87e-4332-b758-efd799d30cf9"),
                            InsertedDate = new DateTime(2025, 1, 17, 10, 18, 42, 518, DateTimeKind.Local).AddTicks(9487),
                            IsDeleted = false,
                            Name = "AZ5W2",
                            Price = 699.99m,
                            Status = (byte)1,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = new Guid("15c05556-7f63-42d2-8fe7-d17b88a18424"),
                            CategoryId = new Guid("66beb5ff-ca68-40b1-a516-c06901b2af03"),
                            Description = "KHT5TP8KQI9R6BGB1DC0",
                            InsertedBy = new Guid("8bfa8403-c87e-4332-b758-efd799d30cf9"),
                            InsertedDate = new DateTime(2025, 1, 17, 10, 18, 42, 518, DateTimeKind.Local).AddTicks(9487),
                            IsDeleted = false,
                            Name = "5MC5E",
                            Price = 699.99m,
                            Status = (byte)1,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = new Guid("b2ff580f-1d81-4a5c-a67e-1e5c017b07b1"),
                            CategoryId = new Guid("3865a01a-e2ab-44ac-8545-0e951468e25e"),
                            Description = "51ID8SAEWWER52D3QZ8H",
                            InsertedBy = new Guid("8bfa8403-c87e-4332-b758-efd799d30cf9"),
                            InsertedDate = new DateTime(2025, 1, 17, 10, 18, 42, 518, DateTimeKind.Local).AddTicks(9487),
                            IsDeleted = false,
                            Name = "T7G0X",
                            Price = 699.99m,
                            Status = (byte)1,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = new Guid("937a6548-9d16-4f94-b72f-6bbeb86b6ba1"),
                            CategoryId = new Guid("47fe4807-c4fc-4f89-ac70-0a9729c453a4"),
                            Description = "VTWIJ8VMPLQBB938ZGFV",
                            InsertedBy = new Guid("8bfa8403-c87e-4332-b758-efd799d30cf9"),
                            InsertedDate = new DateTime(2025, 1, 17, 10, 18, 42, 518, DateTimeKind.Local).AddTicks(9487),
                            IsDeleted = false,
                            Name = "8WMNL",
                            Price = 699.99m,
                            Status = (byte)1,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = new Guid("1e4397bf-131c-4bc4-80b0-36609f12114f"),
                            CategoryId = new Guid("5b34c52a-ec54-458b-bf4a-98de6fb69ac8"),
                            Description = "G9J0M021SSKCTI0PD06P",
                            InsertedBy = new Guid("8bfa8403-c87e-4332-b758-efd799d30cf9"),
                            InsertedDate = new DateTime(2025, 1, 17, 10, 18, 42, 518, DateTimeKind.Local).AddTicks(9487),
                            IsDeleted = false,
                            Name = "DI1J0",
                            Price = 699.99m,
                            Status = (byte)1,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = new Guid("c86fa0ed-1244-4a82-8f1a-d73f785ed243"),
                            CategoryId = new Guid("80a96349-60f4-44ca-86df-d9d10136ccfd"),
                            Description = "SJSWL7QO0EN65DY1F9L6",
                            InsertedBy = new Guid("8bfa8403-c87e-4332-b758-efd799d30cf9"),
                            InsertedDate = new DateTime(2025, 1, 17, 10, 18, 42, 518, DateTimeKind.Local).AddTicks(9487),
                            IsDeleted = false,
                            Name = "NL0KP",
                            Price = 699.99m,
                            Status = (byte)1,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = new Guid("1e1106b3-6f66-41ed-95a1-31808ef03557"),
                            CategoryId = new Guid("e14ab559-a6a5-4f46-9955-9470cd906202"),
                            Description = "2JZYU09FSQKMUOANSSJV",
                            InsertedBy = new Guid("8bfa8403-c87e-4332-b758-efd799d30cf9"),
                            InsertedDate = new DateTime(2025, 1, 17, 10, 18, 42, 518, DateTimeKind.Local).AddTicks(9487),
                            IsDeleted = false,
                            Name = "1N4SF",
                            Price = 699.99m,
                            Status = (byte)1,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = new Guid("eed9fe1f-29d4-4571-8d3d-620f2ec95275"),
                            CategoryId = new Guid("dc25e4e3-c1a7-4521-b1c0-e732943ecc07"),
                            Description = "P79Z8G89C5EEQ2XDLDTN",
                            InsertedBy = new Guid("8bfa8403-c87e-4332-b758-efd799d30cf9"),
                            InsertedDate = new DateTime(2025, 1, 17, 10, 18, 42, 518, DateTimeKind.Local).AddTicks(9487),
                            IsDeleted = false,
                            Name = "AC88Q",
                            Price = 699.99m,
                            Status = (byte)1,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = new Guid("4c946dba-3653-408d-a57f-712ba28cc3a3"),
                            CategoryId = new Guid("b3f4b0a9-a73f-418a-bfb1-2c885bd34ed5"),
                            Description = "KYN3LRP2HGRUQSX69NX2",
                            InsertedBy = new Guid("8bfa8403-c87e-4332-b758-efd799d30cf9"),
                            InsertedDate = new DateTime(2025, 1, 17, 10, 18, 42, 518, DateTimeKind.Local).AddTicks(9487),
                            IsDeleted = false,
                            Name = "NRS92",
                            Price = 699.99m,
                            Status = (byte)1,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = new Guid("870a7e22-e966-4cbd-b3f3-fa1d303a6e2a"),
                            CategoryId = new Guid("a41c1967-b118-4a98-afcc-8ee9929e12be"),
                            Description = "4RLBNMK8CVXW4UWSUNR3",
                            InsertedBy = new Guid("8bfa8403-c87e-4332-b758-efd799d30cf9"),
                            InsertedDate = new DateTime(2025, 1, 17, 10, 18, 42, 518, DateTimeKind.Local).AddTicks(9487),
                            IsDeleted = false,
                            Name = "UFH9S",
                            Price = 699.99m,
                            Status = (byte)1,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = new Guid("1de09164-e4c1-43ab-b0d9-95251ccd8cde"),
                            CategoryId = new Guid("6ff655b0-b1aa-40bd-acba-df07dfd61600"),
                            Description = "HMTINU5XOWA9773IHVSC",
                            InsertedBy = new Guid("8bfa8403-c87e-4332-b758-efd799d30cf9"),
                            InsertedDate = new DateTime(2025, 1, 17, 10, 18, 42, 518, DateTimeKind.Local).AddTicks(9487),
                            IsDeleted = false,
                            Name = "EW4GY",
                            Price = 699.99m,
                            Status = (byte)1,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = new Guid("c5032b06-bab2-4329-9ae7-8143fbac6a71"),
                            CategoryId = new Guid("5c6c4f20-9ac2-421e-8416-45fd0fba87ff"),
                            Description = "OES0UO5U67ZV3TFPTNFO",
                            InsertedBy = new Guid("8bfa8403-c87e-4332-b758-efd799d30cf9"),
                            InsertedDate = new DateTime(2025, 1, 17, 10, 18, 42, 518, DateTimeKind.Local).AddTicks(9487),
                            IsDeleted = false,
                            Name = "WM1DV",
                            Price = 699.99m,
                            Status = (byte)1,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = new Guid("d24ad066-7425-4275-afe5-d5259be670e8"),
                            CategoryId = new Guid("9b184e88-d905-4835-9e4f-20e9be869270"),
                            Description = "SUM1QRDFELZEFZB58ZYB",
                            InsertedBy = new Guid("8bfa8403-c87e-4332-b758-efd799d30cf9"),
                            InsertedDate = new DateTime(2025, 1, 17, 10, 18, 42, 518, DateTimeKind.Local).AddTicks(9487),
                            IsDeleted = false,
                            Name = "STIUA",
                            Price = 699.99m,
                            Status = (byte)1,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = new Guid("7012047f-a9fc-442f-8a88-5ad8212c570c"),
                            CategoryId = new Guid("9b184e88-d905-4835-9e4f-20e9be869270"),
                            Description = "6W2TRQGULS3PHCUNVJ62",
                            InsertedBy = new Guid("8bfa8403-c87e-4332-b758-efd799d30cf9"),
                            InsertedDate = new DateTime(2025, 1, 17, 10, 18, 42, 518, DateTimeKind.Local).AddTicks(9487),
                            IsDeleted = false,
                            Name = "EOVRX",
                            Price = 699.99m,
                            Status = (byte)1,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = new Guid("a7b14531-69dd-4b87-9ad7-994788b517ea"),
                            CategoryId = new Guid("0c0eea9e-9a72-496a-b30f-69ab6c629473"),
                            Description = "LN8SQVMA1ZALJOTJY9ZO",
                            InsertedBy = new Guid("8bfa8403-c87e-4332-b758-efd799d30cf9"),
                            InsertedDate = new DateTime(2025, 1, 17, 10, 18, 42, 518, DateTimeKind.Local).AddTicks(9487),
                            IsDeleted = false,
                            Name = "N20E1",
                            Price = 699.99m,
                            Status = (byte)1,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = new Guid("d03de71a-a8e0-40c7-be1d-5e08d70a5d61"),
                            CategoryId = new Guid("0c0eea9e-9a72-496a-b30f-69ab6c629473"),
                            Description = "VSL90KJBY4KJN9U04YAP",
                            InsertedBy = new Guid("8bfa8403-c87e-4332-b758-efd799d30cf9"),
                            InsertedDate = new DateTime(2025, 1, 17, 10, 18, 42, 518, DateTimeKind.Local).AddTicks(9487),
                            IsDeleted = false,
                            Name = "3UE0Q",
                            Price = 699.99m,
                            Status = (byte)1,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = new Guid("443df9b3-6231-411e-9fe9-00dc031f2abb"),
                            CategoryId = new Guid("7199fd0a-cc03-46f0-9d21-2ad2e1ef8cbe"),
                            Description = "X1XMP8RGBGUIF9JMF0DA",
                            InsertedBy = new Guid("8bfa8403-c87e-4332-b758-efd799d30cf9"),
                            InsertedDate = new DateTime(2025, 1, 17, 10, 18, 42, 518, DateTimeKind.Local).AddTicks(9487),
                            IsDeleted = false,
                            Name = "6TGAL",
                            Price = 699.99m,
                            Status = (byte)1,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = new Guid("f7cb324f-fbe3-4ea8-9190-3bb4940a3be7"),
                            CategoryId = new Guid("7199fd0a-cc03-46f0-9d21-2ad2e1ef8cbe"),
                            Description = "ADMEOWMYIS1TLEXIKUVO",
                            InsertedBy = new Guid("8bfa8403-c87e-4332-b758-efd799d30cf9"),
                            InsertedDate = new DateTime(2025, 1, 17, 10, 18, 42, 518, DateTimeKind.Local).AddTicks(9487),
                            IsDeleted = false,
                            Name = "T6JYB",
                            Price = 699.99m,
                            Status = (byte)1,
                            StockQuantity = 50
                        });
                });

            modelBuilder.Entity("ProductManagement.Domain.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("InsertedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("UserType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8bfa8403-c87e-4332-b758-efd799d30cf9"),
                            Email = "Admin@urwave.com",
                            InsertedDate = new DateTime(2025, 1, 17, 10, 18, 42, 518, DateTimeKind.Local).AddTicks(9624),
                            IsActive = true,
                            IsDeleted = false,
                            Password = "f99c5521e65bcf281a101f9aa73351179c8e4daf",
                            UserName = "admin",
                            UserType = 1
                        });
                });

            modelBuilder.Entity("ProductManagement.Domain.Models.Category", b =>
                {
                    b.HasOne("ProductManagement.Domain.Models.Category", "ParentCategory")
                        .WithMany()
                        .HasForeignKey("ParentCategoryId");

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("ProductManagement.Domain.Models.Product", b =>
                {
                    b.HasOne("ProductManagement.Domain.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
